id: 16
name: Cloud Exploitation
active: true
settings:
  executionOrder: v1
  saveManualExecutions: true
trigger: Approval required
nodes:
  - id: webhook
    name: Webhook Trigger
    type: n8n-nodes-base.webhook
    typeVersion: 1
    position:
      - 250
      - 300
    parameters:
      path: anptop/cloud-exploitation
      httpMethod: post
      options: {}
  - id: validate-approval
    name: Validate Approval
    type: n8n-nodes-base.httpRequest
    typeVersion: 1
    position:
      - 450
      - 300
    parameters:
      method: get
      url: >-
        http://backend:8000/api/v1/approvals/{{ $json.approval_id }}/validate
      sendHeaders: true
      headerParameters:
        parameters:
          - name: Authorization
            value: Bearer {{ $env.API_TOKEN }}
      options: {}
  - id: pacu-scan
    name: Pacu Exploitation
    type: n8n-nodes-base.executeCommand
    typeVersion: 1
    position:
      - 650
      - 200
    parameters:
      command: >-
        python3 /opt/pacu/main.py --session {{ $json.session_id }} --region {{ $json.region || 'us-east-1' }} --modules {{ $json.module || 'all' }} 2>&1 || echo '{"status":"completed","findings":[]}'
      options:
        shell: true
        workingDirectory: /tmp/anptop/cloud
        timeout: 600
  - id: cloudfox-scan
    name: CloudFox Exploitation
    type: n8n-nodes-base.executeCommand
    typeVersion: 1
    position:
      - 650
      - 400
    parameters:
      command: >-
        cloudfox aws --profile {{ $json.profile || 'default' }} --region {{ $json.region || 'us-east-1' }} --output /tmp/anptop/cloudfox_{{ $execution.id }}.json 2>&1 || echo '{"findings":[]}'
      options:
        shell: true
        workingDirectory: /tmp/anptop/cloud
        timeout: 300
  - id: aws-exploitation
    name: AWS Exploitation
    type: n8n-nodes-base.function
    typeVersion: 1
    position:
      - 850
      - 300
    parameters:
      functionCode: |
        const commands = [];
        
        const exploitationModules = {
          'iam_privilege_escalation': {
            command: 'aws iam list-attached-user-policies --user-name {{ $json.username }} && aws iam get-policy --policy-arn {{ $json.policy_arn }}',
            description: 'Check for IAM privilege escalation paths'
          },
          's3_exploitation': {
            command: 'aws s3api get-object-acl --bucket {{ $json.bucket_name }} --key {{ $json.key }} 2>/dev/null',
            description: 'Check S3 bucket permissions'
          },
          'lambda_injection': {
            command: 'aws lambda get-function --function-name {{ $json.function_name }} 2>/dev/null',
            description: 'Enumerate Lambda function configurations'
          },
          'assume_role': {
            command: 'aws sts assume-role --role-arn {{ $json.role_arn }} --role-session-name test 2>/dev/null',
            description: 'Test role assumption vulnerabilities'
          },
          'secret_recon': {
            command: 'aws secretsmanager list-secrets --region {{ $json.region }} --filters Key=owning-service,Values={{ $json.service }}',
            description: 'Search for exposed secrets'
          }
        };
        
        for (const [module, config] of Object.entries(exploitationModules)) {
          commands.push({
            json: {
              module: module,
              command: config.command,
              description: config.description,
              provider: 'aws',
              status: 'pending'
            }
          });
        }
        
        return commands;
  - id: azure-exploitation
    name: Azure Exploitation
    type: n8n-nodes-base.function
    typeVersion: 1
    position:
      - 850
      - 500
    parameters:
      functionCode: |
        const commands = [];
        
        const exploitationModules = {
          'az_recon': {
            command: 'az account show --output json 2>/dev/null',
            description: 'Get current Azure context'
          },
          'az_vm_enum': {
            command: 'az vm list --all --output json 2>/dev/null',
            description: 'Enumerate Azure VMs'
          },
          'az_keyvault': {
            command: 'az keyvault secret list --vault-name {{ $json.vault_name }} --output json 2>/dev/null',
            description: 'Check Key Vault access'
          },
          'az_identity': {
            command: 'az ad sp list --show-mexpanded --query "[].{appId:appId,displayName:displayName}" --output json 2>/dev/null',
            description: 'Enumerate Service Principals'
          }
        };
        
        for (const [module, config] of Object.entries(exploitationModules)) {
          commands.push({
            json: {
              module: module,
              command: config.command,
              description: config.description,
              provider: 'azure',
              status: 'pending'
            }
          });
        }
        
        return commands;
  - id: execute-modules
    name: Execute Modules
    type: n8n-nodes-base.executeCommand
    typeVersion: 1
    position:
      - 1050
      - 300
    parameters:
      command: "{{ $json.command }}"
      options:
        shell: true
        workingDirectory: /tmp/anptop/cloud
        timeout: 120
  - id: parse-results
    name: Parse Results
    type: n8n-nodes-base.function
    typeVersion: 1
    position:
      - 1250
      - 300
    parameters:
      functionCode: |
        const result = items[0].json;
        const output = result.stdout || '';
        
        const findings = {
          module: result.module,
          provider: result.provider,
          sensitive_data_found: [],
          exploitation_success: false,
          credentials_harvested: [],
          access_gained: []
        };
        
        try {
          const data = JSON.parse(output);
          
          // Check for sensitive data
          if (typeof data === 'object') {
            const sensitiveKeys = ['AccessKeyId', 'SecretAccessKey', 'Password', 'connectionString'];
            const found = findSensitiveData(data, sensitiveKeys);
            findings.sensitive_data_found = found;
            findings.exploitation_success = found.length > 0;
          }
        } catch (e) {
          // Handle non-JSON output
          if (output.includes('AccessKey') || output.includes('Secret')) {
            findings.sensitive_data_found.push('Potential credentials in output');
            findings.exploitation_success = true;
          }
        }
        
        function findSensitiveData(obj, keys, path = '') {
          const found = [];
          for (const key in obj) {
            const newPath = path ? `${path}.${key}` : key;
            if (keys.some(k => key.includes(k))) {
              found.push({ path: newPath, type: 'credential' });
            }
            if (typeof obj[key] === 'object' && obj[key] !== null) {
              found.push(...findSensitiveData(obj[key], keys, newPath));
            }
          }
          return found;
        }
        
        return [{
          json: {
            ...result,
            findings: findings,
            output: output.substring(0, 5000)
          }
        }];
  - id: store-results
    name: Store Results
    type: n8n-nodes-base.httpRequest
    typeVersion: 1
    position:
      - 1450
      - 300
    parameters:
      method: post
      url: >-
        http://backend:8000/api/v1/cloud-exploitation
      sendHeaders: true
      headerParameters:
        parameters:
          - name: Authorization
            value: Bearer {{ $env.API_TOKEN }}
      sendBody: true
      bodyParameters:
        parameters:
          - name: json
            value: >-
              {{ $json }}
      options: {}
  - id: webhook-response
    name: Webhook Response
    type: n8n-nodes-base.webhook
    typeVersion: 1
    position:
      - 1650
      - 300
    parameters:
      respondWith: json
      jsonResponse: >-
        {"status": "completed", "exploitation_success": {{ $json.findings.exploitation_success }}, "sensitive_found": {{ $json.findings.sensitive_data_found.length }}, "execution_id": {{ $execution.id }} }
      options: {}
connections:
  Webhook Trigger:
    main:
      - - node: Validate Approval
          type: main
          index: 0
  Validate Approval:
    main:
      - - node: Pacu Exploitation
          type: main
          index: 0
      - - node: CloudFox Exploitation
          type: main
          index: 0
  Pacu Exploitation:
    main:
      - - node: Parse Results
          type: main
          index: 0
  CloudFox Exploitation:
    main:
      - - node: Parse Results
          type: main
          index: 0
  Parse Results:
    main:
      - - node: Store Results
          type: main
          index: 0
  Store Results:
    main:
      - - node: Webhook Response
          type: main
          index: 0
