"""
ANPTOP Backend - Core Module
"""

from app.core.config import settings, get_settings
from app.core.security import (
    verify_password,
    get_password_hash,
    create_access_token,
    create_refresh_token,
    decode_token,
    get_current_user,
    get_current_active_user,
    generate_mfa_secret,
    get_mfa_uri,
    generate_mfa_qr_code,
    verify_mfa_token,
    activate_kill_switch,
    deactivate_kill_switch,
    kill_switch_active,
    audit_log,
    generate_api_key,
    check_permission,
)
from app.core.tools_config import (
    ALL_SECURITY_TOOLS,
    DISCOVERY_TOOLS,
    SCANNING_TOOLS,
    ENUMERATION_TOOLS,
    VULNERABILITY_ASSESSMENT_TOOLS,
    EXPLOITATION_TOOLS,
    POST_EXPLOITATION_TOOLS,
    LATERAL_MOVEMENT_TOOLS,
    EVIDENCE_COLLECTION_TOOLS,
    PAYMENT_SYSTEMS_TOOLS,
    BLOCKCHAIN_TOOLS,
    API_SECURITY_TOOLS,
    SOCIAL_ENGINEERING_TOOLS,
    ToolCategory,
    OSType,
    ToolStatus,
    SecurityTool,
    tool_manager,
)
from app.core.tool_executor import (
    tool_executor,
    ToolExecutor,
    ToolExecutionResult,
)

__all__ = [
    # Config
    "settings",
    "get_settings",
    # Security
    "verify_password",
    "get_password_hash",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "get_current_user",
    "get_current_active_user",
    "generate_mfa_secret",
    "get_mfa_uri",
    "generate_mfa_qr_code",
    "verify_mfa_token",
    "activate_kill_switch",
    "deactivate_kill_switch",
    "kill_switch_active",
    "audit_log",
    "generate_api_key",
    "check_permission",
    # Tools Configuration
    "ALL_SECURITY_TOOLS",
    "DISCOVERY_TOOLS",
    "SCANNING_TOOLS",
    "ENUMERATION_TOOLS",
    "VULNERABILITY_ASSESSMENT_TOOLS",
    "EXPLOITATION_TOOLS",
    "POST_EXPLOITATION_TOOLS",
    "LATERAL_MOVEMENT_TOOLS",
    "EVIDENCE_COLLECTION_TOOLS",
    "PAYMENT_SYSTEMS_TOOLS",
    "BLOCKCHAIN_TOOLS",
    "API_SECURITY_TOOLS",
    "SOCIAL_ENGINEERING_TOOLS",
    "ToolCategory",
    "OSType",
    "ToolStatus",
    "SecurityTool",
    "tool_manager",
    # Tool Executor
    "tool_executor",
    "ToolExecutor",
    "ToolExecutionResult",
]
